FROM node:8.11.3-alpine
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --production --silent
COPY . .
EXPOSE 3000
ENV NODE_ENV production
CMD [ "node", "server.js" ]