version: '2.1'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    depends_on:
      - express
  express:
    build:
      context: .
      dockerfile: Dockerfile-express
    ports:
      - 3000:3000
    depends_on:
      - db
    environment: 
      - MONGODB_URI=mongodb://db:27017/my-heroes
  db:
    image: mongo:3.4.16-jessie
    restart: always
    volumes: 
      - /data/db:/data/db
    